[package]
name = "desdec-core"
version = "0.2.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
capstone = { version = "0.14", default-features = false, features = ["std", "full", "arch_arm64"] }
iced-x86 = { version = "1.21", features = ["decoder", "gas"] }
